name: trotziklueger
favicon: null
layout_spectrum: 0.45379
typography_spectrum: 0.74603
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#f0d096'
    - '#fff7e6'
    - '#82783f'
    - '#51582d'
  brandStrength: 0.8125
  lightness: 0.1875
  saturation: 0.25
  rhythmicContrast: 0.25
purpose: []
