name: trotziklueger
favicon: null
layout_spectrum: 0.37840997125022113
typography_spectrum: 0.7527344923000783
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.7649728870019317
  lightness: 0.4860762790776789
  saturation: 0.14712144643999636
  rhythmicContrast: 0.27629407797940075
purpose: []
