typography_spectrum: 0.66395
color:
  brandColors:
    - '#000000'
    - '#f0d096'
    - '#fff7e6'
    - '#82783f'
    - '#51582d'
  brandStrength: 0.75
  lightness: 0.1875
  saturation: 0.125
  rhythmicContrast: 0.25
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.45379
analytics:
  google: null
  facebook: null
  twitter: null
name: trotziklueger
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: trotzi klueger
description: ich komme mit friedlichen Absichten
purpose: []
